### ISSUE TITLE
Error in counting the Hijri Months

### ISSUE THREAD

**Issue by bm2ilabs** [maherelgamil/arabicdatetime#1]
Hello i had an issue with the Hijri month the error was that there is no offset 12 and it is true , the count of the array is 12 but the array key start with 0 so it has to be 11 instead 

to fix this 

``` php
$month = $hiriDateArray['month'] - 1 ;
$monthName = array_values($this->hijriMonths)[$hiriDateArray['month'] - 1];
```

**Comment by maherelgamil** [comment]
Thanks for you @bm2ilabs https://github.com/maherelgamil/arabicdatetime/commit/a808f2eca7320f84a6ba91b6c340530c988cc4ce
