### ISSUE TITLE
Not support Laravel 6.2

### ISSUE THREAD

**Issue by nadjib** [maherelgamil/arabicdatetime#14]
I can't install this package with Laravel 6.2

**Comment by maherelgamil** [comment]
now support laravel 6 & 7 

Update your package & Enjoy!

**Comment by Daniyal-Javani** [comment]
Same problem, seems the latest version in Packagist is still `4.0.2`
https://packagist.org/packages/maherelgamil/arabicdatetime#4.0.2

Anyway my problem solved by adding `"maherelgamil/arabicdatetime": "dev-master"` to composer json
