### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by imranalii** [maherelgamil/arabicdatetime#9]
Translation is not working under Laravel 5.4. 

I found the problem in following file:
`vendor/maherelgamil/arabicdatetime/src/Maherelgamil/Arabicdatetime/Arabicdatetime.php
`
Following function parameters are invalid:
`trans("arabicdatetime::months.".strtolower($month) , [] , null , 'ar');`

'ar' should be third param instead of fourth.

Please fix & update code.

Thanks.

**Comment by maherelgamil** [comment]
This issue was fixed in this pull request https://github.com/maherelgamil/arabicdatetime/pull/10 thanks for @imranali1 @arezk84 :) <3
